server.port=8081
spring.application.name=kefu-backend
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/kefu2?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=${DB_USERNAME:kefu2}
spring.datasource.password=${DB_PASSWORD:kefu2}
jwt.secret=xQ7#pZ9&vM2!kL4*sN1@bR3^fT5$gH8%jW6+eY0~dU
app.public-url=https://hxzc33.cc.cd
app.frontend-url=https://hxzc33.cc.cd
app.admin.username=hxzc33
app.admin.password=123456
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
tron.receive.address=TPYX8gWBdkgE9eTXk8QWirhpD9qBwp1Nqv
tron.api.key=
tron.usdt.contract=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t
tron.api.url=https://api.trongrid.io
recharge.usdt.rate=7.2
recharge.expire.minutes=10
bot.api.password=xQ7pZ9vM2kL4sN1bR3
